name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:

  lint-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Lint README
        run: markdownlint "**/*.md"

  docker-compose-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate docker compose
        run: docker compose config

  stack-start-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start stack
        run: docker compose up -d

      - name: Wait services
        run: sleep 30

      - name: List containers
        run: docker ps

      - name: Stop stack
        run: docker compose down